# Imagen oficial de Tomcat con Java 17
FROM tomcat:9.0-jdk17-temurin

# Limpiamos las aplicaciones por defecto
RUN rm -rf /usr/local/tomcat/webapps/*

# Copiamos todo el contenido de webapp a la raíz de Tomcat
COPY src/main/webapp/ /usr/local/tomcat/webapps/ROOT/

# Exponemos el puerto
EXPOSE 8080

# Iniciamos Tomcat
CMD ["catalina.sh", "run"]